### ISSUE TITLE
RubyDoc.info host support

### ISSUE THREAD

**Issue by andy4thehuynh** [lucapette/vim-ruby-doc#7]
I want to set "http://www.rubydoc.info/" as my host. I have this in my vimrc

`let g:ruby_doc_ruby_host='https://www.rubydoc.info/'`

Am I doing it right?

**Comment by lucapette** [comment]
Hey, sorry for letting you wait so long. RubyDoc is set by default this way:

``` vim
let g:ruby_doc_ruby_host='http://rubydoc.info/search/stdlib/core?q='
```

I assume the default isn't working for you?
